### ISSUE TITLE
Read based Assembly Evaluation

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/rfc#183]
Besides our current (reference based and reference free) assembly benchmark interface, there is a way to evaluate assemblies based on the initial reads data.
Bioboxes should provide an interface for these kind of tools.

This issue should be closed when there is

  * A read based assembly benchmark rfc.

  * A schema.

  * A verify command for testing read based assembly benchmark bioboxes.

  * At least one example implementing the interface.

Current Examples:

* (ALE)[https://github.com/AlphaSquad/ALE] Biobox (work in progress) 

* (VALET)[https://github.com/AlphaSquad/VALET] Biobox (work in progress) 

Current RFC: https://github.com/pbelmann/rfc/blob/pbelmann-read-based-assembly-evaluation/container/assembly-evaluation/read-based-assembly-evaluation/rfc.mkd

**Comment by michaelbarton** [comment]
This is a good idea, I would use this in combination with the existing reference based biobox to examine assemblies. I noticed you checked into the CLI an assembly fasta file but not not any reads. Is this an assembly of the existing genome paired reads fastq file.

**Comment by michaelbarton** [comment]
@accopeland, this read-based assembly validator might be useful in combintation with QUAST for evaluating assemblies.

**Comment by michaelbarton** [comment]
The example in the RFC is:

```YAML
---
version: 0.1.0
arguments:
   assemblies:
     - path: /path/to/assembly1/fasta
       id: ray
       type: contig
       format: bioboxes.org:/fasta
   reads:
     path: /path/to/short/read.fastq.gz
     id: lib1
     type: paired
     format: bioboxes.org:/fastq
```

Should this instead be:

```YAML
---
version: 0.1.0
arguments:
   assemblies:
     - path: /path/to/assembly1/fasta
       id: ray
       type: contig
       format: bioboxes.org:/fasta
   reads:
     - path: /path/to/short/read.fastq.gz
       id: ray
       type: paired
       format: bioboxes.org:/fastq
```
I have changed `lib1` to `ray` as I believe the RFC indicates the IDs should match. Is this correct? Also I believe the reads should also be a list.
