### ISSUE TITLE
Parsing and accessing input/output in containers

### ISSUE THREAD

**Issue by fungs** [bioboxes/rfc#85]
Hi, I openend a separate issue as this is related to but independent from how the interfaces are actually defined. If we come up with a structured way to specify and pass information to the container which involves YAML or similar, it should be accessible to the tools immediately without having to go through language parsing. Eventually, this will make it necessary to develop some connecting code which runs inside the container and which allows to access the input and output in an easy way.

Here, I would like to suggest approaches which can transform an XML-like structure into a file and folder based structure which is native to UNIX systems. Examples of such approaches are the /proc and /sys pseudo-filesystems. Earlier versions of Xorg, the well-known display server, where also supporting a  configuration system if I remember correctly. The way I'm thinking of at the moment would be to set up such a structure in memory (e.g. in the RAM-disk /dev/shm) by parsing the YAML input and creating the corresponding folders, files and file links. Advantages of this approach are

* every tool can access information just by using file paths which have a 1:1 correspondence to the interface definition
* fast and atomic access without having to call external code after initialization
* effective control of read-write modes
* direct implementation of input/output files instead of strings which contain the path to files supporting memory-mapping
* a basic form of validation (file existence check etc.)

**Comment by pbelmann** [comment]
Could you make an example? Do you suggest to move the mounted directories/files to a given directory structure?

**Comment by fungs** [comment]
I would try to avoid any expensive operation on files and solve this via mounts, links etc. This would be more of a common view on the data which is required by the spec and given to the container. Applications in the container can use the view and avoid having to parse the (semi-)structured data. For the simple example which @pbelmann posted in #61

```YAML
---
 version: 0.8.1
 libs: 
    - lib1: 
        path: "/path/inside/the/container/to/lib1"
        parameters: 
         is_paired: true
         avg_ins: 180
    - lib2: 
        path: "/path/inside/the/container/to/lib2"
        parameters: 
         is_paired: true
         avg_ins: 130
 output: "path/inside/the/container/to/contigs/file"
```

the interface could be viewed as

    /bbxs/ifc/version -> contains "0.8.1"
    /bbxs/ifc/libs/lib1/file -> file
    /bbxs/ifc/libs/lib1/parameters/is_paired -> contains "true"
    /bbxs/ifc/libs/lib1/parameters/avg_ins -> contains "180"
    /bbxs/ifc/libs/lib2/file
    /bbxs/ifc/libs/lib2/parameters/is_paired -> contains "true"
    /bbxs/ifc/libs/lib2/parameters/avg_ins -> contains "130"
    /bbxs/ifc/output -> file

This is one of the most convenient representations as the most simple call for an assembler could be something like

    assember -in /bbxs/ifc/libs/lib*/file -out /bbxs/ifc/out
