### ISSUE TITLE
Assembler YAML Schema

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/rfc#86]
Dependent on the final YAML we decide in #61, we need some kind of schema to check against. By using a schema we can ensure that a YAML given to a container has the correct format.

There are three different types of schema we could use:
 * XML with XML schema definition (XSD)
 * JSON with  [JSON-Schema](http://json-schema.org/) or [Rx](http://rx.codesimply.com/) ,
 * YAML with [kwalify](http://www.kuwata-lab.com/kwalify/) or [Rx](http://rx.codesimply.com/)

In #61 we decided to use YAML but because of the importance of JSON I chose a library that can validate JSON and YAML. Furthermore we could convert our [YAML to JSON](http://yamltojson.com/) :

#### Pros
* schemas can be used in JavaScript, Ruby, Perl, PHP and Python.
* can validate YAML and JSON
* can have arrays, maps with different type elements
* resulting schemas are much more concise
* easy to extend type system

#### Cons
* documentation lacks examples, so a little harder to grasp
* validation errors don’t contain any useful information

Pros and Cons are based on [this](http://danlucraft.com/blog/2008/11/yaml-document-schemas/) blog which is from 2008.

### Example
I want the following yaml files to be accepted:

```YAML
#1 correct
---
  version: "0.8.1"
  arguments: 
    - 
      path: "/path/inside/the/container/to/lib2"
      type: "paired_fastq"
      metadata: 
        - 
          key: "insert_size"
          value: 200
    - 
      path: "/path/inside/the/container/to/lib3"
      type: "paired_fastq"
      metadata: 
        - 
          key: "insert_size"
          value: 200
```

and 

```YAML
#2 correct
---
  version: "0.8.1"
  arguments: 
    - 
      path: "/path/inside/the/container/to/lib2"
      type: "paired_fastq"
      metadata: 
        - 
          key: "insert_size"
          value: 200
    - 
      path: "/path/inside/the/container/to/lib3"
      type: "paired_fastq"
```

are accepted but not the following:

```YAML
#3 wrong
---
  version: "0.8.1"
  arguments: 
    - 
      path: "/path/inside/the/container/to/lib2"
      type: "anything"
      metadata: 
        - 
          key: "insert_size"
          value: 200
    - 
      path: "/path/inside/the/container/to/lib3"
      type: "paired_fastq"
```
or

```YAML
#4 wrong
---
  version: "0.8.1"
  arguments: 
    - 
      path: "/path/inside/the/container/to/lib2"
      type: "fastq"
      metadata: 
        - 
          key: "insert_size"
          value: 200
    - 
          type: "paired_fastq"
```

So I build the Rx specific schema that just accepts the yaml 1 and 2:

```YAML
---
  type: "//rec"
  required: 
    version: "//str"
    arguments: 
      type: "//arr"
      contents: 
        type: "//rec"
        required: 
          path: "//str"
          type: 
            type: "//any"
            of: 
              - 
                type: "//str"
                value: "paired_fastq"
              - 
                type: "//str"
                value: "fastq"
        optional: 
          metadata: 
            type: "//arr"
            contents: 
              type: "//any"
              of: 
                - 
                  type: "//rec"
                  required: 
                    key: 
                      type: "//str"
                      value: "insert_size"
                    value: "//num"
```

or in json:

```JSON
{
   "type":"//rec",
   "required":{
      "version":"//str",
      "arguments":{
         "type":"//arr",
         "contents":{
            "type":"//rec",
            "required":{
               "path":"//str",
               "type":{
                  "type":"//any",
                  "of":[
                     {
                          "type":"//str",
                          "value":"paired_fastq"
                     },
                     {
                          "type":"//str",
                          "value":"fastq"
                     }
                  ]
               }
            },
            "optional" :{
               "metadata":{
                  "type" : "//arr",
                  "contents" : {
                        "type":"//any",
                        "of":[
                        {
                          "type":"//rec",
                          "required" : {
                              "key": {
                                "type" : "//str",
                                "value": "insert_size" 
                              },
                              "value": "//num"
                          }
                        }
                       ]  
                  }
               }
            }
         }
      }
   }
}
```

#### Note! I tested the json versions of the above yaml in the rx live [validator](http://rx.codesimply.com/demo.html#demo).
