### ISSUE TITLE
The short read assemblers should generate a valid output YAML file

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#98]
We have agreed on the YAML format for bioboxes in #61. The output generated
YAML file should match this format so the same file is valid for passing to
another container. An example of this might be:

```YAML
---
version: 0.9.0
arguments:
  - fasta:
    - id: auto_generated_id_1
      value: "/path/to/reads"
      type: contig
```

I think this would be valid for a biobox with the signature

    fasta A -> X

**Comment by michaelbarton** [comment]
I made a mistake in the yaml above. The second hyphen should not appear as this is a single fasta, not a list of fasta.

**Comment by pbelmann** [comment]
Why not a list like:

```YAML
---
version: 0.9.0
arguments:
  - fasta:
    - id: auto_generated_id_1
      value: "/path/to/contigs"
      type: contig
    - id: auto_generated_id_2
      value: "/path/to/scaffold"
      type: scaffold
```
